name: Seguro Bici Production Flow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 143.198.105.146 >> ~/.ssh/known_hosts
      - name: Deploy Nest.js backend
        run: |
          ssh -o StrictHostKeyChecking=no gys_user@143.198.105.146 << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            cd ~/var/www/novedades-prod-backend || {
              mkdir -p ~/var/www
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              git clone git@github.com:seguroweb/novedades-backend.git ~/var/www/novedades-prod-backend
              cd ~/var/www/novedades-prod-backend
            }
            git pull origin main
            npm install
            npm run build
            pm2 restart novedades-backend || pm2 start dist/main.js --name "novedades-backend"
            pm2 save
          EOF






